### ISSUE TITLE
Background theming

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#73]
A basic gradient that passes through the main theme colours as shown in the mockup with adjustable waypoints (where the colour changes) so these can later be aligned with headings.

For a general look, observe the mockup as a whole:

![Image](https://user-images.githubusercontent.com/30503695/257632789-b3c054ea-b133-4b49-b24b-407254989749.png)

**Comment by Lordfirespeed** [comment]
I'm concerned that if we hard-code the stops to particular lengths or percentages, viewing on different platforms is gonna be a bad experience as content wrapping will lead to the gradient not lining up in the same way. I think that some kind of programmatic solution is going to be necessary 😬

**Comment by Lordfirespeed** [comment]
It could also be implemented by having separate backgrounds for each section that mesh together. I think I'm gonna give that a go.

**Comment by Lordfirespeed** [comment]
Okay, made some significant progress on this. Will need changing pending updated mockups but I'm happy with what I've got so far.

**Comment by tameTNT** [comment]
> I'm concerned that if we hard-code the stops to particular lengths or percentages, viewing on different platforms is gonna be a bad experience as content wrapping will lead to the gradient not lining up in the same way.

Ah I worded the suggestion badly 😅. What I meant was if there was any way to fix the gradient stops/transitions/waypoints to the actual position of the headers on the document?
So for example, the blue transition would always happen 20px above the FAQ heading no matter the viewport something like that. That way the gradient could adjust dynamically based on the header position influenced by viewport size.

**Comment by tameTNT** [comment]
I can see this is essentially what you've done via the separate gradients! Perfect - the meaning got there one way or another 😅
