### ISSUE TITLE
Landing header section

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#74]
![Image](https://user-images.githubusercontent.com/30503695/257628782-3df7a877-5fd8-4258-aed4-76a397ed2908.png)

Includes:

- Background image
- Overlayed circuit design
- DurHack countdown (involves JS)
- Rocket design (not moving/tied to scroll yet - see other draft)

**Comment by Lordfirespeed** [comment]
I've called this section the 'splash' section in the website source.

**Comment by Lordfirespeed** [comment]
![Image](https://github.com/ducompsoc/durhack/assets/28568841/24274b9c-b2d7-498c-b935-f12b7bcdf23f)

Here's my progress so far - navbar not done yet

**Comment by Lordfirespeed** [comment]
Some things are clearly a little 'off' but I'm sure we'll be able to get that sorted

**Comment by tameTNT** [comment]
Ooo looking amazing thank you!

**Comment by tameTNT** [comment]
Pending further guidance on mobile design.
