### ISSUE TITLE
Introduction section

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#75]
![Image](https://github.com/ducompsoc/durhack/assets/30503695/b6b5a60a-03a9-4051-aea5-3b61e0dda65c)

Original images can be sourced from the Figma file (see project page sidebar)

**Comment by tameTNT** [comment]
Photos can be sourced from [Google Drive](https://drive.google.com/drive/folders/1L7HPur6l4qoPQqgsdaCEZMEqm_Tg-owx?usp=drive_link)

**Comment by tameTNT** [comment]
Glow effect is achieved by blurring a second copy of the constellations by 20px

**Comment by willwoodward** [comment]
Just a small thing (note to self), but should it say "come together" instead of "came together"?

**Comment by tameTNT** [comment]
There is now an updated design for this section (see the initial comment)!

**Comment by willwoodward** [comment]
Have updated the intro design to the new one! Should I make a pull request?
