### ISSUE TITLE
Megateam section

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#77]
![Image](https://github.com/ducompsoc/durhack/assets/30503695/3980b4db-c115-4faa-8444-df8e762c3826)

Should include the megateams icons alongside a short description (when you click learn more) of what the megateams mean for the project.

We can use the placeholder text provided before finalising with the hacker experience team at a later date.

**Comment by tameTNT** [comment]
When loading the megateams SVG icons onto the page you'll need to load them as an object rather than as an image for the constellations to display.

**Comment by willwoodward** [comment]
Loaded the SVGs as an object now!
