### ISSUE TITLE
Meet the team section

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#82]
Last year, this section was interactive showing more information on each member on hover.

![Image](https://github.com/ducompsoc/durhack/assets/30503695/deef9e9b-5189-4951-b8bc-f649570ae30b)

Further discussion on motion/movement can be found on Slack: https://durhack2023-organiser.slack.com/archives/C04KM7JG8VC/p1691142429612829

**Comment by tameTNT** [comment]
Alternative proposed design with less motion potentially:


![Image](https://github.com/ducompsoc/durhack/assets/30503695/a4723e62-c322-4a52-b551-459c6c8c7340)

**Comment by willwoodward** [comment]
Use keyframes for animations

**Comment by willwoodward** [comment]
Animations are working, however there is a stacking issue since I am combining rotations and z-index and pseudo elements. This makes hovering over an item quite difficult.
