### ISSUE TITLE
Schedule section

### ISSUE THREAD

**Issue by tameTNT** [ducompsoc/durhack#83]
_This has not yet been designed/mocked up._

This is the hardest to adapt/modify in any way due to Ethan's wizardry being quite complex. Since it is never abided by anyway, it may be better replaced with a general structure (registration, hacking, deadline, judging, final presentation) and then the potential events throughout (cupstacking, games, etc.).

_Last year:_
![Image](https://user-images.githubusercontent.com/30503695/257631764-8c512532-619c-461e-8919-00b6ee5dc595.png)
_Proposed design:_
![Image](https://github.com/ducompsoc/durhack/assets/30503695/70c67fc9-6764-4411-b469-1c62d9f762fb)

**Comment by willwoodward** [comment]
Was thinking about this, probably easiest to just have 2 SVGs and swap them out responsively
